# Generated by Django 2.0.1 on 2018-01-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NoteBook'),
        ),
    ]
